# Site settings
title: Just saying
email: peterChungaloo@yandex.com
description: > # this means to ignore newlines until "baseurl:"
  Pseudonymous outlet for unpolished thoughts that shouldn't be taken seriously.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anojo.github.io" # the base hostname & protocol for your site
twitter_username: notYet
github_username:  anojo

# Build settings
markdown: kramdown
